# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://de-badkamer.be
baseurl:
title: "de badkamer: Uw wensen op maat"
email:
author:
description:
port: 4000


source 'https://rubygems.org'

gem 'jekyll', '3.1.6'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
end
